import { useState, useEffect } from 'react';
import { BigOHeader } from '../components/bigo/BigOHeader';
import { CodeInput } from '../components/bigo/CodeInput';
import { ExampleSnippets } from '../components/bigo/ExampleSnippets';
import { CaseAnalysis } from '../components/bigo/CaseAnalysis';
import { ComplexityClass } from '../components/bigo/ComplexityChips';
import { ResultSummary } from '../components/bigo/ResultSummary';
import { GrowthIntuition } from '../components/bigo/GrowthIntuition';
import { ComparisonStrip } from '../components/bigo/ComparisonStrip';
import { FormalDefinition } from '../components/bigo/FormalDefinition';
import { DataStructureReference } from '../components/bigo/DataStructureReference';
import { BigOActions } from '../components/bigo/BigOActions';
import { analyzeCode, AnalysisResult } from '../utils/codeAnalyzer';
import { useNavigate } from 'react-router';

interface ComplexityInfo {
  description: string;
  examples: string;
}

const complexityData: Record<ComplexityClass, ComplexityInfo> = {
  'O(1)': {
    description: 'For input size n, runtime is constant regardless of n. Operations complete in fixed time.',
    examples: 'Typical examples: array access, hash table lookup, basic arithmetic.',
  },
  'O(log n)': {
    description: 'For input size n, runtime grows logarithmically. Doubling n adds only one more step.',
    examples: 'Typical examples: binary search, balanced tree operations.',
  },
  'O(n)': {
    description: 'For input size n, runtime grows linearly. Doubling n doubles the time.',
    examples: 'Typical examples: iterating through array, linear search, simple loops.',
  },
  'O(n log n)': {
    description: 'For input size n, runtime grows roughly n × log₂(n). Common in efficient sorting.',
    examples: 'Typical examples: merge sort, heap sort, quicksort (average case).',
  },
  'O(n²)': {
    description: 'For input size n, runtime grows quadratically. Doubling n quadruples the time.',
    examples: 'Typical examples: nested loops, bubble sort, selection sort, insertion sort.',
  },
  'O(2ⁿ)': {
    description: 'For input size n, runtime doubles with each additional element. Grows extremely fast.',
    examples: 'Typical examples: recursive fibonacci, generating power set, subset sum.',
  },
  'O(n!)': {
    description: 'For input size n, runtime grows factorially. One of the slowest growth rates.',
    examples: 'Typical examples: generating permutations, traveling salesman (brute force).',
  },
};

export function BigOCalculator() {
  const navigate = useNavigate();
  const [code, setCode] = useState('');
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [displayComplexity, setDisplayComplexity] = useState<ComplexityClass | null>(null);

  useEffect(() => {
    if (code.trim()) {
      const result = analyzeCode(code);
      setAnalysis(result);
      setDisplayComplexity(null);
    } else {
      setAnalysis(null);
      setDisplayComplexity(null);
    }
  }, [code]);

  const handleCompare = (complexity: ComplexityClass) => {
    setDisplayComplexity(complexity);
  };

  const handleReset = () => {
    setCode('');
    setAnalysis(null);
    setDisplayComplexity(null);
  };

  const handleBack = () => {
    navigate('/');
  };

  const getSummaryText = (): string => {
    const complexity = displayComplexity || analysis?.complexity;
    if (!complexity) return '';

    const info = complexityData[complexity];
    const codePreview = code.split('\n').slice(0, 5).join('\n') + (code.split('\n').length > 5 ? '\n...' : '');

    let summary = `Big O Notation Analysis\n${'='.repeat(50)}\n\n`;
    summary += `Time Complexity: ${complexity}\n`;

    if (analysis) {
      summary += `Confidence Level: ${analysis.confidence}\n`;
      if (analysis.spaceComplexity) {
        summary += `Space Complexity: ${analysis.spaceComplexity}\n`;
      }
      summary += `\nCase Analysis:\n`;
      if (analysis.bestCase) summary += `  • Best Case: ${analysis.bestCase}\n`;
      if (analysis.averageCase) summary += `  • Average Case: ${analysis.averageCase}\n`;
      if (analysis.worstCase) summary += `  • Worst Case: ${analysis.worstCase}\n`;
    }

    summary += `\nCode Analyzed:\n${'-'.repeat(50)}\n${codePreview}\n${'-'.repeat(50)}\n\n`;
    summary += `Description:\n${info.description}\n\n`;
    summary += `Common Examples:\n${info.examples}\n\n`;

    if (analysis && analysis.patterns.length > 0) {
      summary += `Detected Patterns:\n`;
      analysis.patterns.forEach(pattern => {
        summary += `  • ${pattern}\n`;
      });
      summary += `\n`;
    }

    summary += `Analysis Details:\n`;
    if (analysis) {
      summary += `${analysis.reasoning}\n\n`;
    }

    summary += `Generated by Dev Calculators - Big O Analyzer`;

    return summary;
  };

  const currentComplexity = displayComplexity || analysis?.complexity || null;
  const hasResult = analysis !== null;
  const currentInfo = currentComplexity ? complexityData[currentComplexity] : null;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#0f1419] pb-24">
      <BigOHeader onBack={handleBack} />

      <CodeInput value={code} onChange={setCode} />

      <ExampleSnippets onSelectExample={setCode} />

      {analysis && (
        <CaseAnalysis
          bestCase={analysis.bestCase}
          averageCase={analysis.averageCase}
          worstCase={analysis.worstCase}
          spaceComplexity={analysis.spaceComplexity}
        />
      )}

      {hasResult && currentInfo && (
        <>
          <ResultSummary
            complexity={currentComplexity}
            description={currentInfo.description}
            examples={currentInfo.examples}
          />

          <GrowthIntuition complexity={currentComplexity} />

          <ComparisonStrip
            currentComplexity={currentComplexity}
            onCompare={handleCompare}
          />
        </>
      )}

      {/* Cheat Sheet and Formal Definition */}
      <div className="px-4 mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
        <DataStructureReference />
        <FormalDefinition />
      </div>

      <div className="h-8" />

      <BigOActions
        onReset={handleReset}
        summaryText={getSummaryText()}
        hasResult={hasResult}
      />
    </div>
  );
}
